version: "3"
services:
  db:
    image: mysql:8.0.33
    restart: always
    environment:
      - "MYSQL_ROOT_PASSWORD=root"
      - "MYSQL_DATABASE=tsmcdocs"
      - "MYSQL_USER=admin"
      - "MYSQL_PASSWORD=admin"
    volumes:
      - ./mysql_data:/var/lib/mysql
    networks:
      - default
    expose:
      - "3306"
    ports:
      - "3305:3306"
  
  backend:
    depends_on:
      - db
    build:
      context: .
      dockerfile: Dockerfile
    image: gin-documentation-backend
    restart: always
    user: root
    networks:
      - default
    links:
      - "db"
    ports:
      - "8000:8000"

  web:
    depends_on:
      - backend
    build:
      context: quasar-project/.
      target: "production-stage"
    image: quasar-documentation-frontend
    ports:
    - "8080:80"
